
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of AccountWriterServiceModel
 *
 * @constructor
 */
AccountWriterServiceModel = function (obj) {
    if(!obj) {
        this.idGender = null;     
        this.firstName = null;     
        this.name = null;     
        this.email = null;     
        this.phone = null;     
        this.birthday = null;     
        this.address1 = null;     
        this.city = null;     
        this.postalCode = null;     
        this.countryCode = null;     
        this.nationality = null;     
        this.optin = null;     
        this.company = null;     
        this.address2 = null;     
        this.billAddress1 = null;     
        this.billAddress2 = null;     
        this.billCity = null;     
        this.billPostalCode = null;     
        //Append to variable dictionary
        this._variableDict['idGender'] = 'IdGender';
        this._variableDict['firstName'] = 'FirstName';
        this._variableDict['name'] = 'Name';
        this._variableDict['email'] = 'Email';
        this._variableDict['phone'] = 'Phone';
        this._variableDict['birthday'] = 'Birthday';
        this._variableDict['address1'] = 'Address1';
        this._variableDict['city'] = 'City';
        this._variableDict['postalCode'] = 'PostalCode';
        this._variableDict['countryCode'] = 'CountryCode';
        this._variableDict['nationality'] = 'Nationality';
        this._variableDict['optin'] = 'Optin';
        this._variableDict['company'] = 'Company';
        this._variableDict['address2'] = 'Address2';
        this._variableDict['billAddress1'] = 'BillAddress1';
        this._variableDict['billAddress2'] = 'BillAddress2';
        this._variableDict['billCity'] = 'BillCity';
        this._variableDict['billPostalCode'] = 'BillPostalCode';
    } else {
        this.idGender = obj.IdGender;
        this.firstName = obj.FirstName;
        this.name = obj.Name;
        this.email = obj.Email;
        this.phone = obj.Phone;
        this.birthday = new Date(obj.Birthday);
        this.address1 = obj.Address1;
        this.city = obj.City;
        this.postalCode = obj.PostalCode;
        this.countryCode = obj.CountryCode;
        this.nationality = obj.Nationality;
        this.optin = obj.Optin;
        this.company = obj.Company;
        this.address2 = obj.Address2;
        this.billAddress1 = obj.BillAddress1;
        this.billAddress2 = obj.BillAddress2;
        this.billCity = obj.BillCity;
        this.billPostalCode = obj.BillPostalCode;
        //Append to variable dictionary
        this._variableDict['idGender'] = 'IdGender';
        this._variableDict['firstName'] = 'FirstName';
        this._variableDict['name'] = 'Name';
        this._variableDict['email'] = 'Email';
        this._variableDict['phone'] = 'Phone';
        this._variableDict['birthday'] = 'Birthday';
        this._variableDict['address1'] = 'Address1';
        this._variableDict['city'] = 'City';
        this._variableDict['postalCode'] = 'PostalCode';
        this._variableDict['countryCode'] = 'CountryCode';
        this._variableDict['nationality'] = 'Nationality';
        this._variableDict['optin'] = 'Optin';
        this._variableDict['company'] = 'Company';
        this._variableDict['address2'] = 'Address2';
        this._variableDict['billAddress1'] = 'BillAddress1';
        this._variableDict['billAddress2'] = 'BillAddress2';
        this._variableDict['billCity'] = 'BillCity';
        this._variableDict['billPostalCode'] = 'BillPostalCode';
    }
};

AccountWriterServiceModel.prototype = new BaseModel();
AccountWriterServiceModel.prototype.constructor = AccountWriterServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
AccountWriterServiceModel.prototype.getIdGender = function() {
    return this.idGender;
};

/**
 * Setter for IdGender
 * 
 * @param {int} value 
 */
AccountWriterServiceModel.prototype.setIdGender = function(value) {
    this.idGender = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getFirstName = function() {
    return this.firstName;
};

/**
 * Setter for FirstName
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setFirstName = function(value) {
    this.firstName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getEmail = function() {
    return this.email;
};

/**
 * Setter for Email
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setEmail = function(value) {
    this.email = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getPhone = function() {
    return this.phone;
};

/**
 * Setter for Phone
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setPhone = function(value) {
    this.phone = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {dateTime}
 */
AccountWriterServiceModel.prototype.getBirthday = function() {
    return this.birthday;
};

/**
 * Setter for Birthday
 * 
 * @param {dateTime} value 
 */
AccountWriterServiceModel.prototype.setBirthday = function(value) {
    this.birthday = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getAddress1 = function() {
    return this.address1;
};

/**
 * Setter for Address1
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setAddress1 = function(value) {
    this.address1 = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getCity = function() {
    return this.city;
};

/**
 * Setter for City
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setCity = function(value) {
    this.city = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getPostalCode = function() {
    return this.postalCode;
};

/**
 * Setter for PostalCode
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setPostalCode = function(value) {
    this.postalCode = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getCountryCode = function() {
    return this.countryCode;
};

/**
 * Setter for CountryCode
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setCountryCode = function(value) {
    this.countryCode = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AccountWriterServiceModel.prototype.getNationality = function() {
    return this.nationality;
};

/**
 * Setter for Nationality
 * 
 * @param {string} value 
 */
AccountWriterServiceModel.prototype.setNationality = function(value) {
    this.nationality = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
AccountWriterServiceModel.prototype.getOptin = function() {
    return this.optin;
};

/**
 * Setter for Optin
 * 
 * @param {bool} value 
 */
AccountWriterServiceModel.prototype.setOptin = function(value) {
    this.optin = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
AccountWriterServiceModel.prototype.getCompany = function() {
    return this.company;
};

/**
 * Setter for Company
 * 
 * @param {string|null} value 
 */
AccountWriterServiceModel.prototype.setCompany = function(value) {
    this.company = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
AccountWriterServiceModel.prototype.getAddress2 = function() {
    return this.address2;
};

/**
 * Setter for Address2
 * 
 * @param {string|null} value 
 */
AccountWriterServiceModel.prototype.setAddress2 = function(value) {
    this.address2 = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
AccountWriterServiceModel.prototype.getBillAddress1 = function() {
    return this.billAddress1;
};

/**
 * Setter for BillAddress1
 * 
 * @param {string|null} value 
 */
AccountWriterServiceModel.prototype.setBillAddress1 = function(value) {
    this.billAddress1 = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
AccountWriterServiceModel.prototype.getBillAddress2 = function() {
    return this.billAddress2;
};

/**
 * Setter for BillAddress2
 * 
 * @param {string|null} value 
 */
AccountWriterServiceModel.prototype.setBillAddress2 = function(value) {
    this.billAddress2 = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
AccountWriterServiceModel.prototype.getBillCity = function() {
    return this.billCity;
};

/**
 * Setter for BillCity
 * 
 * @param {string|null} value 
 */
AccountWriterServiceModel.prototype.setBillCity = function(value) {
    this.billCity = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
AccountWriterServiceModel.prototype.getBillPostalCode = function() {
    return this.billPostalCode;
};

/**
 * Setter for BillPostalCode
 * 
 * @param {string|null} value 
 */
AccountWriterServiceModel.prototype.setBillPostalCode = function(value) {
    this.billPostalCode = value;
};


module.exports = AccountWriterServiceModel;