
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of CsvFileWriterServiceModel
 *
 * @constructor
 */
CsvFileWriterServiceModel = function (obj) {
    if(!obj) {
        this.idProject = null;     
        this.file = null;     
        this.header = null;     
        this.separator = null;     
        //Append to variable dictionary
        this._variableDict['idProject'] = 'IdProject';
        this._variableDict['file'] = 'File';
        this._variableDict['header'] = 'Header';
        this._variableDict['separator'] = 'Separator';
    } else {
        this.idProject = obj.IdProject;
        this.file = obj.File;
        this.header = obj.Header;
        this.separator = obj.Separator;
        //Append to variable dictionary
        this._variableDict['idProject'] = 'IdProject';
        this._variableDict['file'] = 'File';
        this._variableDict['header'] = 'Header';
        this._variableDict['separator'] = 'Separator';
    }
};

CsvFileWriterServiceModel.prototype = new BaseModel();
CsvFileWriterServiceModel.prototype.constructor = CsvFileWriterServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
CsvFileWriterServiceModel.prototype.getIdProject = function() {
    return this.idProject;
};

/**
 * Setter for IdProject
 * 
 * @param {int} value 
 */
CsvFileWriterServiceModel.prototype.setIdProject = function(value) {
    this.idProject = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CsvFileWriterServiceModel.prototype.getFile = function() {
    return this.file;
};

/**
 * Setter for File
 * 
 * @param {string} value 
 */
CsvFileWriterServiceModel.prototype.setFile = function(value) {
    this.file = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
CsvFileWriterServiceModel.prototype.getHeader = function() {
    return this.header;
};

/**
 * Setter for Header
 * 
 * @param {bool} value 
 */
CsvFileWriterServiceModel.prototype.setHeader = function(value) {
    this.header = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CsvFileWriterServiceModel.prototype.getSeparator = function() {
    return this.separator;
};

/**
 * Setter for Separator
 * 
 * @param {string} value 
 */
CsvFileWriterServiceModel.prototype.setSeparator = function(value) {
    this.separator = value;
};


module.exports = CsvFileWriterServiceModel;