
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of PayinServiceModel
 *
 * @constructor
 */
PayinServiceModel = function (obj) {
    if(!obj) {
        this.amount = null;     
        this.returnUrl = null;     
        //Append to variable dictionary
        this._variableDict['amount'] = 'Amount';
        this._variableDict['returnUrl'] = 'ReturnUrl';
    } else {
        this.amount = obj.Amount;
        this.returnUrl = obj.ReturnUrl;
        //Append to variable dictionary
        this._variableDict['amount'] = 'Amount';
        this._variableDict['returnUrl'] = 'ReturnUrl';
    }
};

PayinServiceModel.prototype = new BaseModel();
PayinServiceModel.prototype.constructor = PayinServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
PayinServiceModel.prototype.getAmount = function() {
    return this.amount;
};

/**
 * Setter for Amount
 * 
 * @param {int} value 
 */
PayinServiceModel.prototype.setAmount = function(value) {
    this.amount = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
PayinServiceModel.prototype.getReturnUrl = function() {
    return this.returnUrl;
};

/**
 * Setter for ReturnUrl
 * 
 * @param {string|null} value 
 */
PayinServiceModel.prototype.setReturnUrl = function(value) {
    this.returnUrl = value;
};


module.exports = PayinServiceModel;