
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of ProjectWriterServiceModel
 *
 * @constructor
 */
ProjectWriterServiceModel = function (obj) {
    if(!obj) {
        this.idTemplate = null;     
        this.title = null;     
        this.estimatedTimePerTask = null;     
        this.nbSupplierPerTask = null;     
        this.amountWithoutTaxPerTask = null;     
        this.automaticValidation = null;     
        this.maxEndDate = null;     
        this.idCertification = null;     
        this.urlNotification = null;     
        //Append to variable dictionary
        this._variableDict['idTemplate'] = 'IdTemplate';
        this._variableDict['title'] = 'Title';
        this._variableDict['estimatedTimePerTask'] = 'EstimatedTimePerTask';
        this._variableDict['nbSupplierPerTask'] = 'NbSupplierPerTask';
        this._variableDict['amountWithoutTaxPerTask'] = 'AmountWithoutTaxPerTask';
        this._variableDict['automaticValidation'] = 'AutomaticValidation';
        this._variableDict['maxEndDate'] = 'MaxEndDate';
        this._variableDict['idCertification'] = 'IdCertification';
        this._variableDict['urlNotification'] = 'UrlNotification';
    } else {
        this.idTemplate = obj.IdTemplate;
        this.title = obj.Title;
        this.estimatedTimePerTask = obj.EstimatedTimePerTask;
        this.nbSupplierPerTask = obj.NbSupplierPerTask;
        this.amountWithoutTaxPerTask = obj.AmountWithoutTaxPerTask;
        this.automaticValidation = obj.AutomaticValidation;
        this.maxEndDate = new Date(obj.MaxEndDate);
        this.idCertification = obj.IdCertification;
        this.urlNotification = obj.UrlNotification;
        //Append to variable dictionary
        this._variableDict['idTemplate'] = 'IdTemplate';
        this._variableDict['title'] = 'Title';
        this._variableDict['estimatedTimePerTask'] = 'EstimatedTimePerTask';
        this._variableDict['nbSupplierPerTask'] = 'NbSupplierPerTask';
        this._variableDict['amountWithoutTaxPerTask'] = 'AmountWithoutTaxPerTask';
        this._variableDict['automaticValidation'] = 'AutomaticValidation';
        this._variableDict['maxEndDate'] = 'MaxEndDate';
        this._variableDict['idCertification'] = 'IdCertification';
        this._variableDict['urlNotification'] = 'UrlNotification';
    }
};

ProjectWriterServiceModel.prototype = new BaseModel();
ProjectWriterServiceModel.prototype.constructor = ProjectWriterServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
ProjectWriterServiceModel.prototype.getIdTemplate = function() {
    return this.idTemplate;
};

/**
 * Setter for IdTemplate
 * 
 * @param {int} value 
 */
ProjectWriterServiceModel.prototype.setIdTemplate = function(value) {
    this.idTemplate = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
ProjectWriterServiceModel.prototype.getTitle = function() {
    return this.title;
};

/**
 * Setter for Title
 * 
 * @param {string} value 
 */
ProjectWriterServiceModel.prototype.setTitle = function(value) {
    this.title = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
ProjectWriterServiceModel.prototype.getEstimatedTimePerTask = function() {
    return this.estimatedTimePerTask;
};

/**
 * Setter for EstimatedTimePerTask
 * 
 * @param {string} value 
 */
ProjectWriterServiceModel.prototype.setEstimatedTimePerTask = function(value) {
    this.estimatedTimePerTask = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
ProjectWriterServiceModel.prototype.getNbSupplierPerTask = function() {
    return this.nbSupplierPerTask;
};

/**
 * Setter for NbSupplierPerTask
 * 
 * @param {int} value 
 */
ProjectWriterServiceModel.prototype.setNbSupplierPerTask = function(value) {
    this.nbSupplierPerTask = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
ProjectWriterServiceModel.prototype.getAmountWithoutTaxPerTask = function() {
    return this.amountWithoutTaxPerTask;
};

/**
 * Setter for AmountWithoutTaxPerTask
 * 
 * @param {int} value 
 */
ProjectWriterServiceModel.prototype.setAmountWithoutTaxPerTask = function(value) {
    this.amountWithoutTaxPerTask = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
ProjectWriterServiceModel.prototype.getAutomaticValidation = function() {
    return this.automaticValidation;
};

/**
 * Setter for AutomaticValidation
 * 
 * @param {bool} value 
 */
ProjectWriterServiceModel.prototype.setAutomaticValidation = function(value) {
    this.automaticValidation = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {dateTime|null}
 */
ProjectWriterServiceModel.prototype.getMaxEndDate = function() {
    return this.maxEndDate;
};

/**
 * Setter for MaxEndDate
 * 
 * @param {dateTime|null} value 
 */
ProjectWriterServiceModel.prototype.setMaxEndDate = function(value) {
    this.maxEndDate = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int|null}
 */
ProjectWriterServiceModel.prototype.getIdCertification = function() {
    return this.idCertification;
};

/**
 * Setter for IdCertification
 * 
 * @param {int|null} value 
 */
ProjectWriterServiceModel.prototype.setIdCertification = function(value) {
    this.idCertification = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
ProjectWriterServiceModel.prototype.getUrlNotification = function() {
    return this.urlNotification;
};

/**
 * Setter for UrlNotification
 * 
 * @param {string|null} value 
 */
ProjectWriterServiceModel.prototype.setUrlNotification = function(value) {
    this.urlNotification = value;
};


module.exports = ProjectWriterServiceModel;