
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TaskValidationWriterServiceModel
 *
 * @constructor
 */
TaskValidationWriterServiceModel = function (obj) {
    if(!obj) {
        this.idTask = null;     
        this.state = null;     
        //Append to variable dictionary
        this._variableDict['idTask'] = 'IdTask';
        this._variableDict['state'] = 'State';
    } else {
        this.idTask = obj.IdTask;
        this.state = obj.State;
        //Append to variable dictionary
        this._variableDict['idTask'] = 'IdTask';
        this._variableDict['state'] = 'State';
    }
};

TaskValidationWriterServiceModel.prototype = new BaseModel();
TaskValidationWriterServiceModel.prototype.constructor = TaskValidationWriterServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int|null}
 */
TaskValidationWriterServiceModel.prototype.getIdTask = function() {
    return this.idTask;
};

/**
 * Setter for IdTask
 * 
 * @param {int|null} value 
 */
TaskValidationWriterServiceModel.prototype.setIdTask = function(value) {
    this.idTask = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
TaskValidationWriterServiceModel.prototype.getState = function() {
    return this.state;
};

/**
 * Setter for State
 * 
 * @param {string|null} value 
 */
TaskValidationWriterServiceModel.prototype.setState = function(value) {
    this.state = value;
};


module.exports = TaskValidationWriterServiceModel;