
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TemplateQuestionWriterServiceModel
 *
 * @constructor
 */
TemplateQuestionWriterServiceModel = function (obj) {
    if(!obj) {
        this.title = null;     
        this.require = null;     
        this.idTemplateObjectQuestionType = null;     
        this.order = null;     
        this.option = null;     
        this.choices = null;     
        //Append to variable dictionary
        this._variableDict['title'] = 'Title';
        this._variableDict['require'] = 'Require';
        this._variableDict['idTemplateObjectQuestionType'] = 'IdTemplateObjectQuestionType';
        this._variableDict['order'] = 'Order';
        this._variableDict['option'] = 'Option';
        this._variableDict['choices'] = 'Choices';
    } else {
        this.title = obj.Title;
        this.require = obj.Require;
        this.idTemplateObjectQuestionType = obj.IdTemplateObjectQuestionType;
        this.order = obj.Order;
        this.option = obj.Option;
        this.choices = obj.Choices;
        //Append to variable dictionary
        this._variableDict['title'] = 'Title';
        this._variableDict['require'] = 'Require';
        this._variableDict['idTemplateObjectQuestionType'] = 'IdTemplateObjectQuestionType';
        this._variableDict['order'] = 'Order';
        this._variableDict['option'] = 'Option';
        this._variableDict['choices'] = 'Choices';
    }
};

TemplateQuestionWriterServiceModel.prototype = new BaseModel();
TemplateQuestionWriterServiceModel.prototype.constructor = TemplateQuestionWriterServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
TemplateQuestionWriterServiceModel.prototype.getTitle = function() {
    return this.title;
};

/**
 * Setter for Title
 * 
 * @param {string} value 
 */
TemplateQuestionWriterServiceModel.prototype.setTitle = function(value) {
    this.title = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
TemplateQuestionWriterServiceModel.prototype.getRequire = function() {
    return this.require;
};

/**
 * Setter for Require
 * 
 * @param {bool} value 
 */
TemplateQuestionWriterServiceModel.prototype.setRequire = function(value) {
    this.require = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TemplateQuestionWriterServiceModel.prototype.getIdTemplateObjectQuestionType = function() {
    return this.idTemplateObjectQuestionType;
};

/**
 * Setter for IdTemplateObjectQuestionType
 * 
 * @param {int} value 
 */
TemplateQuestionWriterServiceModel.prototype.setIdTemplateObjectQuestionType = function(value) {
    this.idTemplateObjectQuestionType = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TemplateQuestionWriterServiceModel.prototype.getOrder = function() {
    return this.order;
};

/**
 * Setter for Order
 * 
 * @param {int} value 
 */
TemplateQuestionWriterServiceModel.prototype.setOrder = function(value) {
    this.order = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
TemplateQuestionWriterServiceModel.prototype.getOption = function() {
    return this.option;
};

/**
 * Setter for Option
 * 
 * @param {string|null} value 
 */
TemplateQuestionWriterServiceModel.prototype.setOption = function(value) {
    this.option = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array|null}
 */
TemplateQuestionWriterServiceModel.prototype.getChoices = function() {
    return this.choices;
};

/**
 * Setter for Choices
 * 
 * @param {array|null} value 
 */
TemplateQuestionWriterServiceModel.prototype.setChoices = function(value) {
    this.choices = value;
};


module.exports = TemplateQuestionWriterServiceModel;