
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TemplateInstructionWriterServiceModel
 *
 * @constructor
 */
TemplateInstructionWriterServiceModel = function (obj) {
    if(!obj) {
        this.instruction = null;     
        this.order = null;     
        //Append to variable dictionary
        this._variableDict['instruction'] = 'Instruction';
        this._variableDict['order'] = 'Order';
    } else {
        this.instruction = obj.Instruction;
        this.order = obj.Order;
        //Append to variable dictionary
        this._variableDict['instruction'] = 'Instruction';
        this._variableDict['order'] = 'Order';
    }
};

TemplateInstructionWriterServiceModel.prototype = new BaseModel();
TemplateInstructionWriterServiceModel.prototype.constructor = TemplateInstructionWriterServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
TemplateInstructionWriterServiceModel.prototype.getInstruction = function() {
    return this.instruction;
};

/**
 * Setter for Instruction
 * 
 * @param {string} value 
 */
TemplateInstructionWriterServiceModel.prototype.setInstruction = function(value) {
    this.instruction = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TemplateInstructionWriterServiceModel.prototype.getOrder = function() {
    return this.order;
};

/**
 * Setter for Order
 * 
 * @param {int} value 
 */
TemplateInstructionWriterServiceModel.prototype.setOrder = function(value) {
    this.order = value;
};


module.exports = TemplateInstructionWriterServiceModel;