
/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TemplateColumnWriterServiceModel
 *
 * @constructor
 */
TemplateColumnWriterServiceModel = function (obj) {
    if(!obj) {
        this.idTemplateColumnType = null;     
        this.column = null;     
        this.order = null;     
        //Append to variable dictionary
        this._variableDict['idTemplateColumnType'] = 'IdTemplateColumnType';
        this._variableDict['column'] = 'Column';
        this._variableDict['order'] = 'Order';
    } else {
        this.idTemplateColumnType = obj.IdTemplateColumnType;
        this.column = obj.Column;
        this.order = obj.Order;
        //Append to variable dictionary
        this._variableDict['idTemplateColumnType'] = 'IdTemplateColumnType';
        this._variableDict['column'] = 'Column';
        this._variableDict['order'] = 'Order';
    }
};

TemplateColumnWriterServiceModel.prototype = new BaseModel();
TemplateColumnWriterServiceModel.prototype.constructor = TemplateColumnWriterServiceModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TemplateColumnWriterServiceModel.prototype.getIdTemplateColumnType = function() {
    return this.idTemplateColumnType;
};

/**
 * Setter for IdTemplateColumnType
 * 
 * @param {int} value 
 */
TemplateColumnWriterServiceModel.prototype.setIdTemplateColumnType = function(value) {
    this.idTemplateColumnType = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TemplateColumnWriterServiceModel.prototype.getColumn = function() {
    return this.column;
};

/**
 * Setter for Column
 * 
 * @param {int} value 
 */
TemplateColumnWriterServiceModel.prototype.setColumn = function(value) {
    this.column = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
TemplateColumnWriterServiceModel.prototype.getOrder = function() {
    return this.order;
};

/**
 * Setter for Order
 * 
 * @param {int} value 
 */
TemplateColumnWriterServiceModel.prototype.setOrder = function(value) {
    this.order = value;
};


module.exports = TemplateColumnWriterServiceModel;