/**
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "http://api.foulefactory.com",

    //The username to use with basic authentication
    //TODO: Replace the BasicAuthUserName with an appropriate value
    basicAuthUserName : "TODO: Replace",

    //The password to use with basic authentication
    //TODO: Replace the BasicAuthPassword with an appropriate value
    basicAuthPassword : "TODO: Replace"

};

module.exports = configuration;

